services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7023:3000"
    environment:
      - NODE_EcNV=production
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - umuhinzilink-net

networks:
  umuhinzilink-net:
    driver: bridge